### ISSUE TITLE
статья не собирается

### ISSUE THREAD

**Issue by anaderi** [Mikari/disser#7]
```
cd first_paper
make
```
> pandoc: Could not find data file /usr/local/Cellar/pandoc/1.17.2/share/x86_64-osx-ghc-8.0.1/pandoc-1.17.2//Users/mikari/.pandoc/templates/html.template

**Comment by Mikari** [comment]
Там в makefile такое:

 Location of Pandoc support files.
PREFIX = /Users/mikari/.pandoc
Я из твоего примера так взял )

**Comment by anaderi** [comment]
fixed pdf creation
